name: Binnentuin - Backend deploy
on:
  push:
    # Negeer commits die zijn gemaakt in:
    paths-ignore:
      - '.github/**'
      - 'extra/**'
      - 'README.md'
      - LICENSE
    # De branch waarop het getriggerd wordt
    branches: dev

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: nathanheffley/laravel-phpunit-action@master
      - name: Laravel PHPunit test
        run: |
          composer install --prefer-dist
          cp .env.example .env
          php artisan key:generate
          php vendor/bin/phpunit
        working-directory: ./laravel
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: phpunit
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v1
      - name: Create .env file
        run: 'echo "$ENV_FILE" > .env'
        shell: bash
        env:
          ENV_FILE: ${{secrets.DOT_ENV}}
        working-directory: ./laravel
      - name: Docker registry login
        # run: docker login ${{ secrets.DOCKER_REGISTRY }}:5000
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      # Build image
      - name: Create new docker image
        run: docker build -t studenttechlife/plant:backend .
        working-directory: ./laravel
      # Push new docker image
      - name: Push docker image
        run: docker push studenttechlife/plant:backend
      # Deploy to swarm
      - name: Deploy to swarm
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker service update --image studenttechlife/plant:backend plant_backend
          host: ${{ secrets.DOCKER_VPN }}
          username: plant
          privateKey: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}