name: Binnentuinapp

on:
  push:
    # De branch waarop het getriggerd wordt
    branches: dev

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # - uses: nathanheffley/laravel-phpunit-action@master
      - name: Laravel PHPunit test
        run: |
          cd ./laravel
          composer install --prefer-dist
          cp .env.example .env
          php artisan key:generate
          php vendor/bin/phpunit
        working-directory: ./laravel
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: phpunit
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: mbstring, bcmath
      - name: Composer install
        run: composer install
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Run Deployment
        env:
          DOT_ENV: ${{ secrets.DOT_ENV }}
          APP_HOST: ${{ secrets.APP_HOST }}
          APP_DEPLOY_PATH: ${{ secrets.APP_DEPLOY_PATH }}
          APP_DEPLOY_USER: ${{ secrets.APP_DEPLOY_USER }}
          APP_DEPLOY_DEFAULT: ${{ secrets.APP_DEPLOY_DEFAULT }}
        run: php artisan deploy -vvv